project:
  description: A short description of the project
  name: envcontainer
  version: 0.0.1
container:
  ports:
    - 22:2229
  shell: bash
  build: |
    FROM alpine:3.18
    RUN apk add --no-cache gcompat libstdc++ curl shadow sudo git openssh-server bash && \
    ssh-keygen -A &&  \
    mkdir -p /var/run/sshd && sed -i 's/AllowTcpForwarding.*/AllowTcpForwarding yes/' /etc/ssh/sshd_config

    # ADD USER    
    RUN groupadd -g {{ exec "id" "-g" }} envcontainer && \
        useradd -ms /bin/bash -u {{ exec "id" "-g" }} -g envcontainer envcontainer && \
        echo 'envcontainer:envcontainer' | chpasswd && \
        echo "envcontainer ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    USER envcontainer

    CMD ["sudo", "/usr/sbin/sshd", "-D"]