project:
  description: A short description of the project
  name: envcontainer
  version: 0.0.1

container:
  # shell: bash  # Optional: shell to use inside the container (default: bash)
  # ports:
  #   - "8080:80"  # Optional: host:container port mapping
  build: |
    FROM alpine:3.18
    RUN apk add --no-cache bash

  # network_mode: "host"  # Optional: Docker network_mode
  # networks:
  #   - name: mynet
  #     external: true

# always_update: false  # Optional: pull/update image before starting
# auto_stop: false      # Optional: stop container after run

# mounts:  # Optional: bind/volume mounts
# - type: bind
#   source: ./
#   target: /workdir
#   readonly: false
